version: "3.8"

services:
  api:
    image: proyecto1-api:1.0
    ports:
      - "8080:8080"
    networks:
      - red-interna
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: "1234"
      DB_NAME: proyecto1db
      SERVER_PORT: 8080
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - db

  db:
    image: postgres:15
    networks:
      - red-interna
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: proyecto1db
    volumes:
      - datos-postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  red-interna:
    driver: overlay

volumes:
  datos-postgres:
